services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 8080:80
    image: app:vue
    container_name: vue-container
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M