services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 80:8080
    image: app:vue
    container_name: vue-container
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 1024M